# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

armadillo_solve <- function(A, b) {
    .Call('_bios735_armadillo_solve', PACKAGE = 'bios735', A, b)
}

one_or_exp <- function(x) {
    .Call('_bios735_one_or_exp', PACKAGE = 'bios735', x)
}

random_walk2 <- function(n, lambda) {
    .Call('_bios735_random_walk2', PACKAGE = 'bios735', n, lambda)
}

